@baseUrl = http://localhost:4002
### GET Books
POST {{baseUrl}}/users/create
Content-Type: application/json

{
    "uid": "123",
    "email": "email@gada.com",
    "name": "Lester 1"
}

###
@userid = 123
GET {{baseUrl}}/users/{{userid}}